name: Create Deployment

on:
  push:
    branches:
      - main

jobs:
  create_deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Register deployment
        id: register-deployment
        uses: actions/github-script@v6
        with:
          script: |
            const deployment = await github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.ref,
              auto_merge: false,
              required_contexts: [],
              environment: 'Test environment',
              description: 'Test deployment',
              transient_environment: true,
              production_environment: false,
            }).then(result => result.data)

            return deployment;

      - name: Set deployment status
        run: |
          DEPLOYMENT_ID="$($DEPLOYMENT_RESULT | jq .id)"

          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            /repos/$GITHUB_REPO/deployments/$DEPLOYMENT_ID/statuses \
            -f state='success' \
            -f log_url='https://google.de'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
          DEPLOYMENT_RESULT: ${{ toJSON(steps.register-deployment.outputs.result) }}
